### ISSUE TITLE
Add Gradient Adjustment

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#49] opened 2017-11-22 19:26 UTC
Inspired by this video: https://vimeo.com/240910267, where I saw some shots where the sky was clearly darkened with a graduated filter.

Opening an issue just to remember.

How it looks in Lightroom:
![Lightroom](https://picturecorrect-wpengine.netdna-ssl.com/wp-content/uploads/2017/06/lightroom-grad-filter-3.jpg)

Would look great in landscapes and stuff.

Of course colour wheels is probably coming before.

**Comment by masc4ii** [comment] 2017-11-22 19:47
Haha, I wanted to ask this too! ;-) But you like to do that with which parameters? All, or just exposure?

**Comment by ilia3101** [comment] 2017-11-22 20:47
Probably a simplified set of parameters, stuff like simplifying the white balance (like lightroom does it think) and probably without the sharpening/chroma blur. Maybe a good time will be after OpenCL is implemented as well cos this is probably slow.

**Comment by bouncyball-git** [comment] 2017-11-23 06:25
@ilia3101 

I always thought that pure mac devel e.g. cocoa and avfoundation are sucking out all your cool inspiration. You would do so lot more in processing otherwise ;)

**Comment by masc4ii** [comment] 2017-11-23 07:53
From the GUI side, the starting point is equal to the wbPicker. But the click&drag will be funny to implement. The lines could be drawn using a second semitransparent scene in the QGraphicsView. So the image has not to be redrawn, when the lines are changing (I hope).

**Comment by masc4ii** [comment] 2017-11-23 08:42
I tested: adding a QGraphicsItem to the scene works good. It can be selected and dragged automatically, without any latency, yeah (I added just 4 lines of code for a dragable line, with QGraphicsLineItem).
Problem: the "Zoom: fit" mode will not work so easy, because this is a manual zoom - so the line is not zoomed in the right way. If "fit" is disabled, no problem.

**Comment by bouncyball-git** [comment] 2017-11-23 10:41
Hmm... cool

**Comment by ilia3101** [comment] 2017-11-23 10:55
@bouncyball-git yeah the Mac stuff is really annoying. Sometimes feel like giving up on it, but sometimes it has been useful for me to me to be able to add a button here or there to test new processing stuff, and someone once said they like it :D

Been getting inspiration for new processing ideas from papers. There's a lot of simple stuff that's really cool that i want to add soon.

**Comment by ilia3101** [comment] 2017-11-23 10:55
@masc4ii hope does it look? I think two dragable points is enough to control it

**Comment by masc4ii** [comment] 2017-11-23 10:58
I can't upload an image... ImgBB does not work :-(

**Comment by ilia3101** [comment] 2017-11-23 10:59
I found out you can just drag it on to the comment editor, try it

**Comment by masc4ii** [comment] 2017-11-23 11:01
![pic](http://fs5.directupload.net/images/171123/mqqs762l.png)
Different hoster now... 
I can place it and turn it.

**Comment by masc4ii** [comment] 2017-11-23 11:07
So I think... parameters could be:
anchorPoint(x,y)
angle(alpha)
radius(length)
This would be the same parameters, for a (how is it called in english?) radial gradient. I only would have to change the graphics element and it would work identical... okay, you don't need the angle then.

**Comment by ilia3101** [comment] 2017-11-23 11:14
Oo nice

I don't know what the best parameter system would be, what do you think of the anchor point, and the other point (anchor point moved by radius at angle), not sure which way would be simpler to do in processing.

Maybe we should also use a floating point, 0 to 1 instead of pixels, as that would be transferable when copying settings between clips of different resolutions. If we even want to copy this adjustment...

**Comment by masc4ii** [comment] 2017-11-23 11:16
Or with two lines: a mixture between Lightroom and DaVinci:
![pic](http://fs5.directupload.net/images/171123/tku7ooh4.png)

Yes, floating point is also a nice idea. This would also work better with my "self-scaled" "zoom: fit" mode.

**Comment by iFloris** [comment] 2017-11-23 16:23
> yeah the Mac stuff is really annoying. Sometimes feel like giving up on it, but sometimes it has been useful for me to me to be able to add a button here or there to test new processing stuff, and someone once said they like it :D
That could be me. I really like the cocoa app. But if it hampers progress to support multiple architectures, perhaps focussing on the most future proof would be better.
Regardless, I stand in awe of the progress that you all are making with this app. 👏

**Comment by ilia3101** [comment] 2017-11-23 18:03
@iFloris haha 🤣, it was you! (but I like it too). Don't worry, I probably won't give it up, as it is what I use to write the processing/mlv code and test new features, so I kind of need it for testing really quick and easily. It has a little bit of sentimental value as well. And it is good reference for anyone wanting to write a Cocoa app without XCode.

**Comment by masc4ii** [comment] 2017-11-23 22:06
I now can draw the lines exactly like in Lightroom. Click, drag, release - it is painted the whole time. 
@ilia3101 : you have the choice between (I have now both, at least in int x,y, but float should be no problem):
- Anchor point, Final Point
- Anchor point, Angle, Length

**Comment by masc4ii** [comment] 2017-11-24 10:33
This really makes fun to implement!
![pic](https://image.ibb.co/h002YR/Bildschirmfoto_2017_11_24_um_11_26_57.png)
Now we can:
- Paint (click, drag, release)
- Get the parameters of the painted lines
- Show a new Group "Linear Gradient"
- Show parameters in GUI Group
- Edit parameters and lines will follow
- Move already painted lines and GUI again shows parameters
- Zoom around and the lines are still correct
- Hide the lines when Group is collapsed
Really not easy to do in the Qt jungle... but fuuuuun! :o)

Do you already have an idea, how many gradients we want to support? For now I have just one...

**Comment by bouncyball-git** [comment] 2017-11-24 13:24
@masc4ii 

Man this gradient section is fantastic! :) Love this and everything you are doing with love and taste :) including metal knobs :P

**Comment by bouncyball-git** [comment] 2017-11-24 13:27
However if mlv is not imported the gradient tool behaves very strangely ;) I suggest in this case make "enable" check box grayed out.

**Comment by masc4ii** [comment] 2017-11-24 13:44
Thx. Yes... the behaviour is not right yet. That should when no clip is loaded. ;-)

**Comment by ilia3101** [comment] 2017-11-24 20:31
I was planning just one gradient for simplicity. I think light room also has just one (may be wrong tho).
If I'm honest, my way of thinking is simply: If in doubt, imitate how Adobe did it

**Comment by masc4ii** [comment] 2017-11-24 20:51
Adobe has as many the user wants (or his PC gets calculated). But I also would say, we implement one for now.

**Comment by masc4ii** [comment] 2017-12-03 13:18
Update: I changed a lot here, to not kill all the work with the new aspect ratio stretch function. There are now 2 coordinate systems parallel: one for the frame viewer and one for the line painter. If I would sync both, the lines are very ugly. So I stretched only the frame and the lines are calculated different. 
In the end, that works for the starting point, end point and the arrow between this two points. What is not right yet: the start & end line is still 90° to the arrow - but when beeing stretched, this is nearly never correct (correct only for 0°, 90°, 180° & 270°). This has to be fixed one day...

**Comment by bouncyball-git** [comment] 2017-12-03 13:26
Hmm... lot of math because of non standard aspect ratio...

**Comment by masc4ii** [comment] 2017-12-03 13:33
Exactly... most of the math I could do in memory to my school time... but with these lines I have a problem now :-D

**Comment by masc4ii** [comment] 2018-08-29 10:46
More progress:
![bildschirmfoto 2018-08-29 um 12 45 19](https://user-images.githubusercontent.com/30245296/44783071-7fee6800-ab89-11e8-87c9-4cf1654cc1ff.png)

**Comment by bouncyball-git** [comment] 2018-08-29 13:38
Awesomeness!!! You are the MAN!

**Comment by bouncyball-git** [comment] 2018-08-29 13:42
Could  you share Mac version for me? I have macbook with me but have no any development enviroment set up here ( lack of space, because it's 4/5 of the time my dougter's notebook ;) and she will never let me own it full time for devel)

**Comment by masc4ii** [comment] 2018-08-29 14:07
Sry guys... it is not all commited... there are still some bugs I'll fix this evening (Windows hangs completely as expected, receipt realization is missing and other little "nice" bugs). After that I'll upload a version to play with! 😄

**Comment by bouncyball-git** [comment] 2018-08-29 16:49
It really works!!! 🤣

**Comment by masc4ii** [comment] 2018-08-29 17:35
https://www.dropbox.com/s/cvk3gyb564xzh79/MLV%20App%20r1610.zip?dl=0
This one should work better.

**Comment by dannephoto** [comment] 2018-08-29 19:43
Madc. You are doing so much creative stuff these days. Very impressive. Only tested briefly and works great with exposure slider. Could one wish for white balance slider working for this too? And maybe even anility for multiple gradients?

**Comment by masc4ii** [comment] 2018-08-29 20:06
Thanks. Adding WB and contrast could be possible relatively easy... this would mean dublicating even more matrices and functions. 
Adding multiple gradients would be the death for my concept (if there is any) and also for the CPU... 😄 Atm there are several 65535*uint16_t arrays... all these arrays would be there n times... and have to be calculated. It isn't impossible... but...

**Comment by masc4ii** [comment] 2018-08-30 10:30
Added a contrast gradient slider. That was not so difficult... WB should be harder... let's see...

**Comment by ilia3101** [comment] 2018-08-30 21:00
wowowowow amazing 😍😍😍

**Comment by masc4ii** [comment] 2019-02-14 08:01
With the same processing I am able to realize a vignette filter. The problem is, that I can not add it additionally - it would be linear gradient OR vignette. My processing solution is too limiting.

![m05-0608_frame_1](https://user-images.githubusercontent.com/30245296/52771757-07943a00-3037-11e9-91a6-d0812fb03b3e.png)

**Comment by bouncyball-git** [comment] 2019-02-14 10:13
You mean there is no chance to repeat the procedure second time in the processing pipeline? after 1st was over? Do second linear gradient or vignette, whatever?

**Comment by masc4ii** [comment] 2019-02-14 10:29
Right. That means it is possible, but is absolutely not nice. 
Last time I doubled code. Now I would have to double it again, so we have 4 times the code (2x2=4).

**Closed** 2019-04-25 10:38 UTC
Labels: enhancement
