### ISSUE TITLE
Pivot and HSL default points

### ISSUE THREAD

**Issue by orfeas-a** [ilia3101/MLV-App#227] opened 2021-07-09 21:04 UTC
I added these two features in the source code for v1.13. They are pretty trivial but i thought that they could be useful.

**Pivot**
![pivot](https://user-images.githubusercontent.com/87092142/125123971-0da37d80-e100-11eb-9389-dd8b675c6134.png)
This slider controls the pivot point for the contrast. It is useful for adding contrast while keeping the exposure on the subject constant. You can do this by setting its value to the same luminance value as the subject, with 0.00 being the darkest part of the image and 1.00 being the lightest. I have left the default value at 0.75, as it was in the source code. You can see its effect on the waveform as you change the contrast.

**HSL default points**
![hsl](https://user-images.githubusercontent.com/87092142/125131647-b7d4d280-e10b-11eb-87ed-746ea0483c45.png)
Reset curve with default points. Faster and more accurate than doing it by hand.

If anyone is interested i can upload the source code and it can be added in the next version of the app if other users find it useful. I have been using MLVApp for a while and i am glad i can contribute to the project by adding these features! Let me know if i should open a new pull request or do something else (i am new to github).

**Comment by masc4ii** [comment] 2021-07-10 18:11
Hi, very nice to see someone playing with our code! Thank you for your input. 
Especially the pivot slider is very interesting. I really would like to see it in action. Looks easy to realize, if I understood right what you did. ;) 
For the points in HSL elements: I don't understand the advantage of it - you can define and undefine as much points as you like as is. I am a bit scared that it will hinder the workflow?!
Anyway - thanks again for the nice ideas! Did you create a fork and uploaded your changes?

**Comment by orfeas-a** [comment] 2021-07-11 14:32
The code was simple to understand and very well organized so it was easy to implement these ideas!
For the pivot i simply recorded a couple of frames of a grayscale chart to figure out what point remained unchanged when changing the contrast (it would be a good idea to add compatibility for importing png files for such tests in the future, but if i understand correctly the current pipeline applies raw corrections first so i don't know if it would be easy to implement). I found that it was around 0.75 so i looked for this value in the code, replaced it with a variable controlled by the slider and it worked.
For the HSL i only added a new reset button that also adds the default points (the points only show up if you press the button, not by default). I wanted to make all the changes "non-destructive" so that they wouldn't alter the workflow which is already very convenient.
I also added the pivot to the receipt and anywhere else i found the contrast related functions and variables in the code (let me know if i forgot something).
Also, do you know why the contrast is multiplied by 0.65? My guess is that it's probably there to prevent clipping. If we are going to add the pivot i guess we could also leave the contrast without multiplying it to give a bit more control to the users? But it is also understandable if you want to keep the app as user-friendly as possible.
I have created a fork with the changes, not sure what to do next.

**Comment by masc4ii** [comment] 2021-07-13 09:51
Great, thank you! I have not much time in the next weeks, but I'll have a look when I find some time... thanks again!

**Comment by masc4ii** [comment] 2021-08-13 11:47
Hi @orfeas-a ,
now I found some time and tried your work! I must say: nice work! Like it! Also your direct coding work is good. I just would do a tiny change:
you changed void processing_update_contrast_curve(processingObject_t * processing, double pivot); but that wasn't neccessary, because pivot is already part of "processing".

**Comment by orfeas-a** [comment] 2021-08-13 12:45
Thanks for taking the time to check it out!
I was about to clean up the code a little mainly because i noticed a small bug when changing the exposure value from the text box (some values changed by -0.01 when pressing enter) even though i haven't messed with the exposure code. Maybe it is caused by the changes i made in the ui files, i'm not sure if this is possible but i will check it out soon. Also thank you for pointing out the unnecessary pivot argument i'm going to fix this as well!

**Comment by orfeas-a** [comment] 2021-08-16 11:53
I have cleaned up the code but i wasn't able to fix the exposure bug. It looks like a rounding error. Can you try to compile it and see if you get it too? Try the value 1.66

**Comment by masc4ii** [comment] 2021-08-17 14:04
Thank you! Hm... can't really reproduce.... typing 1.66 for exposure and hitting enter brings: 1.66.

**Comment by orfeas-a** [comment] 2021-09-03 13:37
Sorry for the late reply, i was busy this past week. I have created the pull request.

**Comment by masc4ii** [comment] 2021-09-03 17:06
Great! Merged. Thank you! :)

**Closed by masc4ii** 2021-09-03 17:06 UTC
Labels: enhancement
