### ISSUE TITLE
Vertical stripes causes horizontal / grid like artifacts

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#112] opened 2018-10-08 08:55 UTC
Happens when the stripes are severe, more info here: https://www.magiclantern.fm/forum/index.php?topic=22890.new#new

Made me think my sensor was messed up :laughing: (well it still is but not that much)

**Comment by masc4ii** [comment] 2018-10-08 09:18
I have the same problem with my fathers 7D (mainboard exchanged by Canon). I am not sure if it is visible in CR2, but the MLVs look the same as @ilia3101 was showing in ML Forum... 😄 So there is hope, the clips become better!

**Comment by ilia3101** [comment] 2018-10-08 10:03
Wow can't believe Canon wouldn't even calibrate their own column gains!

@bouncyball main replies on that thread to see are #3 and #4

**Comment by masc4ii** [comment] 2018-10-08 18:38
For me it looks like that:
Stripes OFF
![bildschirmfoto 2018-10-08 um 20 28 19](https://user-images.githubusercontent.com/30245296/46627233-16735900-cb3a-11e8-8289-e16b1cc1a801.png)

Stripes ON
![bildschirmfoto 2018-10-08 um 20 28 23](https://user-images.githubusercontent.com/30245296/46627253-225f1b00-cb3a-11e8-808b-0d68484554db.png)

What do you think? The same?

**Comment by ilia3101** [comment] 2018-10-08 20:40
Yep, that's the fine grid pattern I see, makes adding sharpening not nice.

**Comment by bouncyball-git** [comment] 2018-10-09 06:39
Is old mlv_dump correction better in this regard?

**Comment by ilia3101** [comment] 2018-10-09 17:05
Ah sorry for being slow to reply. Yes, old mlv_dump gets rid of these stripes perfectly

**Comment by masc4ii** [comment] 2018-10-09 17:21
Hm... I tried exporting once with MLVApp (VStripes On) and then I mounted same MLV with MLVFS with VStripes On. MLVFS dng looks identical to VStripes Off. So, I don't know if it works there. Do I need a special version of MLVFS (ML Forum told no)?

**Comment by ilia3101** [comment] 2018-10-09 18:42
Try converting to dng with mlv_dump that you can download from mlv_dump forum thread. I know that had no stripes. Or show what's happening

**Comment by masc4ii** [comment] 2018-10-09 18:58
Did that also with mlv_dump now - 3rd time same result. Looks like my 2nd picture above. If you like to try it out: https://www.dropbox.com/s/wbzgtacehlrl2z0/M13-1329_7Dpink.MLV?dl=0

**Comment by ilia3101** [comment] 2018-10-09 21:43
I tried it out converting to DNG with old mlv_dump and with MLV App. Had to average it to get it to export as uncompressed so I used average frame which affected result probably.

Here's exported with MLV App problemativ stripe correction:
![broken](https://user-images.githubusercontent.com/23642861/46700396-a259b380-cc14-11e8-81a3-5224a272b89e.jpg)
You can see a fine grid pattern

Now exported to DNG with old mlv_dump:
![broken_less](https://user-images.githubusercontent.com/23642861/46700415-ae457580-cc14-11e8-9bd2-560b3b5cbd75.jpg)
No fine grid pattern.

Same effect as on my frames.

There's a slight black level difference in the pics making one more purple, ignore that.

**Comment by masc4ii** [comment] 2018-10-10 06:08
No matter how I tried to export the dng - I always had the grid pattern as in your first picture. How exactly have you extracted 2nd one? What was the command (maybe mine was wrong)?

**Comment by ilia3101** [comment] 2018-10-10 06:58
Command was: `mlv_dump mlv_file --dng`

Literally just dragged mlv dump then file on to terminal and added `--dng`.

Maybe the Mac version of mlv dump in the download is different? Were you using the one I mentioned from mlv_dump thread first page?
(The download with versions for different operating systems)

**Comment by bouncyball-git** [comment] 2018-10-10 07:31
Actually I can not see any difference at all :) stripes are all over the white wall under the window.

**Comment by masc4ii** [comment] 2018-10-10 07:54
Could you please paste the link? The mlv_dump's I find, are not able to convert lossless or are from 2018 (and with these I get the same as using MLVApp).

**Comment by bouncyball-git** [comment] 2018-10-10 09:10
Ehh guys I compared raw2dng and mlvfs versions and they are quite different. I have to adapt raw2dng version to mlvapp... it will take time because I have to dig into it deeply, what I hate very much ;)

**Comment by ilia3101** [comment] 2018-10-10 09:58
Ah sorry it was mlv thread not mlv dump thread https://www.magiclantern.fm/forum/index.php?topic=7122.0, downloaded file http://www.magiclantern.fm/modules/modules/mlv_dump.zip/mlv_dump.zip

@bouncyball there is some more stripes on the second one but are you not noticing the very fine pixel grid?

It even makes a moire pattern when I view on my phone:
![screenshot_20181010-100016](https://user-images.githubusercontent.com/23642861/46728772-732a5d00-cc7b-11e8-9616-7d90eb55aeb6.png)

**Comment by masc4ii** [comment] 2018-10-10 10:27
This one works for you? I just get noise... I guess it can't handle lossless. 
This moiree I get also in MLVApp when zooming around.

**Comment by bouncyball-git** [comment] 2018-10-10 10:33
@ilia3101 yes I see it clearly. Very fine net like pattern.
Is it produced after stripe correction or was it present in the original picture?

**Comment by bouncyball-git** [comment] 2018-10-10 11:33
Reproduced and compared!!! Older version does a great job! Definitely MLVFS variant is bad and it has to be changed

**Comment by ilia3101** [comment] 2018-10-10 15:08
Glad you finally reproduced, I don't think the grid patterns were there on original clip. Sorry I've not been too helpful with this I've just had so much life stuff to do 😭

**Comment by ilia3101** [comment] 2018-10-10 16:34
> This one works for you? I just get noise... I guess it can't handle lossless.

I first used MLV App to export an averaged frame of the whole video without compression, that was the way I got a uncompressed file :rofl:

**Comment by masc4ii** [comment] 2018-10-10 18:32
Thanks Ilia! Now I got it. And yes, that looks way better.

**Comment by masc4ii** [comment] 2018-10-12 17:52
https://github.com/ilia3101/MLV-App/commit/7435867d11d7f6b234ac8deaf15588668f114b75 makes it so much better...

**Comment by bouncyball-git** [comment] 2018-10-13 10:09
Hey guys there is still difference between old mlv_dump and mlv app stripe processing, this noticeable mostly in dark areas. Light areal are processed great. 

I've got the idea why this is happening! This is because @ilia3101's sample is 12bit uncompressed!

The main difference between mlv_dump and mlvapp/mlvfs is the fact that all raw processing (corrections) in mlv_dump is done after converting raw data to 14bit and mlvapp/mlvfs does it on original bit depth data, bit unpacked to 16bit thought.

In short all raw processing algos: stripes, bad pixels, etc... been written and tunet for 14bit raw data. I did a bit hoop jumping and fixes during mlv_dump on steroids development to make it work as good as possible for 10/12 bit uncompressed raw (not lossless one, it is completely another story).

So my proposition is: all 10/12 uncompressed raw data should be converted to 14bit (as it is in old good mlv_dump) before all processing is done. This will introduce some extra steps dutin saving DNGs, e.g. donconvert to other bit depths (now it automatically exports DNGs with the depth input MLV has).

What do you think? There are still many MLVs recorded in 10/12bit uncompressed, especially for cameras without lossless support.

**Comment by masc4ii** [comment] 2018-10-13 10:57
Have you tried with commenting out this one pragma line? If it compiles as you checked it in (I had to adapt it a bit) I also get different stripes (correction "works half" only). When commented out it looks awesome for me.

**Comment by bouncyball-git** [comment] 2018-10-13 11:14
Strange, I compile it with pragma under linux and it works. But if it causes issue of course let's get rid of it.

**Comment by bouncyball-git** [comment] 2018-10-13 11:15
I was right. Changes commited to test. With raw data converted to 14bits the image looks awesome even in dark areas (to the left from the hanging leaf)!

**Comment by ilia3101** [comment] 2018-10-13 11:32
Shadows are cleaner now, no signs of grid at all anymore!

**Comment by masc4ii** [comment] 2018-10-13 11:38
That looks so good... unbeliveable what this does to my 7D testclips!

**Comment by bouncyball-git** [comment] 2018-10-13 11:50
I'm glad you both liked!!! :)

mlv_dump original (good rendering)
![mlv_dump](https://user-images.githubusercontent.com/17232233/46905092-92d1b780-ceff-11e8-80e6-a74bdb52e6a5.jpg)
MLV App 12bit
![mlvapp_12bit](https://user-images.githubusercontent.com/17232233/46905096-a2e99700-ceff-11e8-8786-f9d04b00a22c.jpg)
MLV App 14bit fix
![mlvapp_14bit_fix](https://user-images.githubusercontent.com/17232233/46905099-aa10a500-ceff-11e8-8c8a-b3e4b697722e.jpg)

**Comment by bouncyball-git** [comment] 2018-10-13 11:51
Sorry. The difference is more visible after sharpening :)

**Comment by masc4ii** [comment] 2018-10-13 17:34
First found: if I now enable dual iso (it's a non dual iso clip) the image is not black (good), but the stripes are there again (bad). 
I got a new clip from the stripe-producing-7D... in the darks there are still some noticable stripes... :(
![m05-1401stripes_frame_1](https://user-images.githubusercontent.com/30245296/46908162-d1c33580-cf1e-11e8-8976-c367ace43422.png)
https://www.dropbox.com/s/atm91nsuv814ujg/M05-1401stripes.MLV?dl=0

**Comment by bouncyball-git** [comment] 2018-10-13 19:56
Gonna take a look tomorrow.

**Comment by bouncyball-git** [comment] 2018-10-17 15:35
If we do not have more issues let's close it.

**Comment by masc4ii** [comment] 2018-10-17 17:03
In the clip above, I get some few lines in the dark areas. But I think we are not able to get that clean 100%... or do we?! (See blue roof and ocean at the very right.)

**Comment by bouncyball-git** [comment] 2018-10-18 07:04
Yes exactly we can not do anything about is unless Alex thinks about this small issue :). We could ask him. The old mlv_dump does exactly the same.

**Comment by masc4ii** [comment] 2019-04-25 10:36
@bouncyball-git : a1ex write (see link) "My draft patch completely replaced the old algorithm; if you’d like to try it at this stage, I can share it." Have you tried it out? 
If it does not change the artifacts, let's close here... 😄

**Comment by bouncyball-git** [comment] 2019-04-27 16:28
Yeah, but as I remember he never shared that patch (I guess he just forgot about it).

**Closed by bouncyball-git** 2019-04-27 16:28 UTC
Labels: bug
