### ISSUE TITLE
QtApp: Crash on enabling filter

### ISSUE THREAD

**Issue by seescho** [ilia3101/MLV-App#74] opened 2018-02-10 20:21 UTC
With no mlv loaded: no crash
With a mlv loaded: crash
With qt-creator  in debug-mode: no crash ???

When I enable filter, mlvapp freezes. After 10 seconds mlvapp crash: 

> Speicherzugriffsfehler (Speicherabzug geschrieben)

I went back to this commit: "fixed compilation error saying type 'uint16_t' is not defined"
Result: crash

My compile-log tell me this warning for a implicit declaration:

> g++ -o filter.o ../../src/processing/filter/filter.c
> ../../src/processing/filter/filter.c: In function ‘initFilterObject’:
> ../../src/processing/filter/filter.c:41:24: warning: implicit declaration of function ‘fmemopen’; did you mean ‘freopen’? [-Wimplicit-function-declaration]

No clue, if that´s important for the crash

I can reproduce the crash with opensuse-leap and opensuse-tumbleweed

See also discussion on ml-forum: https://www.magiclantern.fm/forum/index.php?topic=20025.msg197099#msg197099

**Comment by bouncyball-git** [comment] 2018-02-11 11:09
I personally never experienced this problem or crashes on ubuntu but we can get rid of fmemopen and use temp files for all OSes.

fmemopen needs  _POSIX_C_SOURCE >= 200809L to not emmit this warning:

#include <stdio.h>

       FILE *fmemopen(void *buf, size_t size, const char *mode);

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       fmemopen():
           Since glibc 2.10:
               _POSIX_C_SOURCE >= 200809L
           Before glibc 2.10:
               _GNU_SOURCE

**Comment by bouncyball-git** [comment] 2018-02-11 11:13
Commit 9ca92de7d87c8afd7d940c486f5dde1bf8122083

**Comment by masc4ii** [comment] 2018-02-11 11:29
@bouncyball-git : Is that enough? Does that delete the temp file on Linux?
```
#ifdef __linux__
#define close_filter(filter) fclose(filter);
#else
#define close_filter(filter) { fclose(filter); remove("__filter_temp__"); }
#endif
```

**Comment by bouncyball-git** [comment] 2018-02-11 11:37
Haha Yes! Right!!! commited.

**Comment by seescho** [comment] 2018-02-11 13:34
No succcess. First freeze and then crash:
QT-Creator tells me:
`The process was ended forcefully.`
I don´t understand, why this works in QT-Creator in debug-mode without any crash, but in normal mode the crash appears.

Not sure at the moment, what I can do to nail down his bug?

**Comment by seescho** [comment] 2018-02-11 13:46
I will load an older version of my OS into a VM and play with it. Maybe filter and Tumbleweed together have hickup at the moment ???

**Comment by seescho** [comment] 2018-02-11 14:23
filter.c line 86 ff

```
/* We need a copy or it gets messed up on many threads */
    genann * net;

    if (filter->filter_option == 0)
        net = genann_copy(filter->net_fj);
    else if (filter->filter_option == 1)
        net = genann_copy(filter->net_vis3);
    else if (filter->filter_option == 2)
        net = genann_copy(filter->net_p400);
    else if (filter->filter_option == 3)
        net = genann_copy(filter->net_toyc);
    else if (filter->filter_option == 4)
        net = genann_copy(filter->net_sepia);
```
        
if I set a return right after genann * net: no crash
if move this return to the end of the "if/else if"-construction: crash

Looks like something happens in genann...

**Comment by seescho** [comment] 2018-02-11 14:42
genann.c    line 153 ff

```
genann *genann_copy(genann const *ann) {

    const int size = sizeof(genann) + sizeof(double) * (ann->total_weights + ann->total_neurons + (ann->total_neurons - ann->inputs));
    genann *ret = malloc(size);
    if (!ret) return 0;

    memcpy(ret, ann, size);

    /* Set pointers. */
    ret->weight = (double*)((char*)ret + sizeof(genann));
    ret->output = ret->weight + ret->total_weights;
    ret->delta = ret->output + ret->total_neurons;

    return ret;
}
```

if I replace the "return ret" by "return 0" : no crash

Now I don´t know, how to proceed ...

**Comment by bouncyball-git** [comment] 2018-02-11 16:07
Is it happening for all MLV clips?

**Comment by seescho** [comment] 2018-02-11 17:05
Yes, 
happens with the old ones, with new ones, happens with mlvs from 600D and from 6D, happens with 10 bit too.

**Comment by masc4ii** [comment] 2018-02-11 17:20
> filter.c line 86 ff
> 
> /* We need a copy or it gets messed up on many threads */
>     genann * net;
> 
>     if (filter->filter_option == 0)
>         net = genann_copy(filter->net_fj);
>     else if (filter->filter_option == 1)
>         net = genann_copy(filter->net_vis3);
>     else if (filter->filter_option == 2)
>         net = genann_copy(filter->net_p400);
>     else if (filter->filter_option == 3)
>         net = genann_copy(filter->net_toyc);
>     else if (filter->filter_option == 4)
>         net = genann_copy(filter->net_sepia);
> 
> if I set a return right after genann * net: no crash
> if move this return to the end of the "if/else if"-construction: crash
> 
> Looks like something happens in genann...

Sounds like the filter parameters were not read (at all or wrong). I had that when inserting new filters and had forgotten some lines...

**Comment by seescho** [comment] 2018-02-11 20:08
It took some time to find out, how to share a folder between host and guest in KVM/QEMU...

I installed openSUSE Leap 42.3 in a VM. That´s the standard openSUSE-version. In Leap I have the same crash... So it´s not Tumbleweed, which forces this crash.

I would like to see the content of some variable (like net). Can someone give me a code-snippet, please, which I can insert?

**Comment by bouncyball-git** [comment] 2018-02-12 09:01
Ehh... I don't think fmemopen was the reason of the crash. The bad thing is I can not reproduce this on ubuntu.
@seescho: can you share the MLV (or small part of it) which crashes the app? Maybe then I could reproduce this.

**Comment by masc4ii** [comment] 2018-02-12 10:51
Get that crash on Ubuntu 12.04 and Qt5.6.3 as well. Unfortunately I don't get a debugger to work on this VM.
Crash is in line 156 in genann.c, called from applyFilterObject(..)

**Comment by bouncyball-git** [comment] 2018-02-12 11:55
Why the f... the filter can not be read on a particular Linux distro? I'm lost...

No crashes on ubuntu 16.04. Never experienced the crash using filters.

BTW I'm using gcc 5.4.0. May be it's that?

**Comment by masc4ii** [comment] 2018-02-12 11:57
No idea. I'm using gcc 4.6.3.

**Comment by ilia3101** [comment] 2018-02-12 11:59
So does this appear to be caused by things going on inside genann library?

**Comment by ilia3101** [comment] 2018-02-12 11:59
Finally a crash I didn't directly cause

**Comment by ilia3101** [comment] 2018-02-12 12:04
Filter files cannot be read for some reason?

**Comment by masc4ii** [comment] 2018-02-12 12:07
Yes I think so - I don't know if they cannot be read. What I know: when applyFilter... is called `filter->net_...` are 0.

**Comment by ilia3101** [comment] 2018-02-12 13:00
Uhh maybe I'll have to find some linux VM I have and see if I can do anything.

**Comment by masc4ii** [comment] 2018-02-12 14:38
Okay, for me `genann_read(..)` returns with NULL.
Just one thought: what happens, if mlvapp has no write permission? I also can't export any file on the desktop via mlvapp on this Linux. I guess mlvapp can't write - so it can't read - then the filter is not loaded the right way, and if filter applied - boooom.

**Comment by ilia3101** [comment] 2018-02-12 14:40
Well maybe fmemopen was only likely to be helping rather than causing problems? As it requires no write permission...

**Comment by masc4ii** [comment] 2018-02-12 14:44
But it was crashing before with fmemopen too.

**Comment by bouncyball-git** [comment] 2018-02-12 14:47
BTW congratulations with passing the 1000 commits :)

Please try the latest commit 77a0740052011f8c73f3f64dc2d5f1054286c1ff

Yes I know that now all this huge filters are on stack but just try if this helps :)

**Comment by masc4ii** [comment] 2018-02-12 14:54
Have no crash... but it does no look as it should look... white, blue, pink, pictures... :-D

**Comment by ilia3101** [comment] 2018-02-12 15:18
I get nice filtered pictures on ubuntu mate vm no problems 😕

**Comment by ilia3101** [comment] 2018-02-12 15:19
```
Yes I know that now all this huge filters are on stack but just try if this helps :)
```
Why will they be huge?

**Comment by masc4ii** [comment] 2018-02-12 15:33
![linux](https://user-images.githubusercontent.com/30245296/36104457-60e74a0c-1012-11e8-9f16-6d5371eaafb5.png)

**Comment by bouncyball-git** [comment] 2018-02-12 15:42
Haha :) When I was a kid I started programming in the end of 80s 88-89 and 640kb mem and 20mb HDD was huge... so it's a habit - everything that is more then 32bytes long is huge for stack ;) (well, I'm kidding)

But seriously on my ubuntu everything works fine, those false colors mean that values are not read correctly.... hmmm...

**Comment by ilia3101** [comment] 2018-02-12 16:17
Argh why is it broken again :((

And I'm extremely confused by that OS

**Comment by seescho** [comment] 2018-02-12 16:50
Back from work...
Cloned from git and compiled 2 minutes ago. Result: No more crash on enabling filter but funny colors.

**Comment by bouncyball-git** [comment] 2018-02-12 16:53
Haha :) When I was a kid I started programming in the end of 80s 88-89 and 640kb mem and 20mb HDD was huge... so it's a habit - everything that is more then 32bytes long is huge for stack ;) (well, I'm kidding)

But seriously on my ubuntu everything works fine, those false colors mean that values are not read correctly.... hmmm...

**Comment by bouncyball-git** [comment] 2018-02-12 16:54
One more question: are you both using 64 bit or 32 bit Linux?

**Comment by bouncyball-git** [comment] 2018-02-12 17:23
Some more polishing, please try again.

**Comment by bouncyball-git** [comment] 2018-02-12 17:48
Now slider works? You can set is to whatever value you want and no funny colors?

**Comment by bouncyball-git** [comment] 2018-02-12 17:50
@masc4ii 
Please confirm that it works with your linux VM as well :)

**Comment by masc4ii** [comment] 2018-02-12 18:43
Hm... also with a 100 on the slider the colors shouldn't be "funny". I use 32bit ubuntu. Will try tomorrow.

**Comment by masc4ii** [comment] 2018-02-13 07:55
Funny colors are still there.

**Comment by bouncyball-git** [comment] 2018-02-13 10:00
Do they appear on 100 of the slider or in any case?

**Comment by bouncyball-git** [comment] 2018-02-13 10:01
I have one last fix for that that I can think of. (32bit linux)

**Comment by masc4ii** [comment] 2018-02-13 10:09
The slider does what it should do - sure: at 100 it is the strongest, at 0 there pic is okay.

**Comment by bouncyball-git** [comment] 2018-02-13 10:27
I mean bad colors appear when any other value than zero is set?

**Comment by bouncyball-git** [comment] 2018-02-13 11:03
@masc4ii 

In your 32bit linux vm do 1 experiment please. Pull last commit, compile and run.

The log output in console will print double values of the filter. please compare them to the originals in film.h.
(they will be printed as double not as long double like in film.h, genann uses double anyway)
If values matched there is something wrong but not with reading of the filter.

If values differ then:

In genann.c in function genann_read() comment this line:
ann->weight[i] = strtod(strtok(NULL, " \t\n"), NULL);
and uncomment this line:
//sscanf(strtok(NULL, " \t\n"), "%le", &ann->weight[i]);

Do the same comparison

**Comment by masc4ii** [comment] 2018-02-13 11:29
All values look like integers: +/-<x>.000000e+00

**Comment by masc4ii** [comment] 2018-02-13 11:47
Got it: it is a localization problem:
if I change the dots to commas in film.h, it works :stuck_out_tongue_closed_eyes:

What can we do here!? Is it possible to change that in the std library?

**Comment by bouncyball-git** [comment] 2018-02-13 12:16
HUH! s..t :) Now everything gets their places. Escho has german loc as you do, but me always use us loc.

I don't know really how to deal with this. Inet is our friend :)

**Comment by ilia3101** [comment] 2018-02-13 12:30
So because of the dots/commas it will now be dependant on where in the world it is compiled on Linux?

**Comment by ilia3101** [comment] 2018-02-13 12:32
Something like:
```
#ifdef GERMANY
#define DOT ","
#else
#define DOT "."
#end
```
If there is a way to test...

**Comment by masc4ii** [comment] 2018-02-13 12:34
The problem is strtod(..) in genann.c, it is locale dependant.

**Comment by bouncyball-git** [comment] 2018-02-13 12:37
Please do what I wrote above comment srttod and uncomment sscanf and try

**Comment by masc4ii** [comment] 2018-02-13 13:15
It happens the same.

**Comment by masc4ii** [comment] 2018-02-13 13:29
Okay. Add this in the first line of genann_read and all is fine here (please test):
`setlocale( LC_ALL, "C" )`
And add `#include <locale.h>`

**Comment by bouncyball-git** [comment] 2018-02-13 13:30
There also "strtod_l" (with last parameter local_t local) but I can not make it work.

**Comment by bouncyball-git** [comment] 2018-02-13 13:44
Thanks, committed. Now I hope everything works as expected.

**Comment by ilia3101** [comment] 2018-02-13 16:42
Yay ❤️ so when is it time to release???????

**Comment by bouncyball-git** [comment] 2018-02-13 16:44
I'm all for it :)

**Comment by masc4ii** [comment] 2018-02-13 17:01
Maybe let's wait for eschos test, and then let's release! 😃

**Comment by bouncyball-git** [comment] 2018-02-13 17:06
Yes this makes sense :)

**Comment by masc4ii** [comment] 2018-02-13 20:06
I already uploaded the OSX version to the release page as draft. @bouncyball-git : when @seescho tells that all is fine, just upload Win64 version and press "Publish release" ;-)

**Comment by bouncyball-git** [comment] 2018-02-14 05:10
@seeschooooooo  where are youuu? :)

**Comment by seescho** [comment] 2018-02-14 16:55
back again :)
Will do some tests later this evening

**Comment by bouncyball-git** [comment] 2018-02-14 17:39
Oh, thanks god, our German jury is here :)

**Comment by seescho** [comment] 2018-02-14 18:45
Hihihi.
The road was long (I dreamed, I came with the ISS): https://seescho.wordpress.com/

I cannot force a crash anymore. And the colors are fine now. I love you all, guys :)

I would say: Let´s go to the new release...

**Comment by masc4ii** [comment] 2018-02-14 18:53
WOW! Great picture! Ist ja der Wahnsinn! 😄

**Comment by masc4ii** [comment] 2018-02-14 18:54
@bouncyball-git : you know what your job is?! 😆

**Comment by bouncyball-git** [comment] 2018-02-14 18:56
@seescho 
I'm sure you are hiding unpublished pics of Elon's Roadster somewhere ;)

@masc4ii 
Yup I know :) What about 32bit one?

**Comment by masc4ii** [comment] 2018-02-14 19:01
I can build the 32bit version... but that needs 2h until my Windows super machine has booted...

**Comment by bouncyball-git** [comment] 2018-02-14 19:04
Nice if you can compile 32bit. I can connect to my work with vpn and log into my Linux box and compile 64bit version in ssh console.

**Comment by seescho** [comment] 2018-02-14 19:16
@bouncyball-git 
Elon´s Roadster? Nope. But I documented The First Contact, some time ago:
https://seescho.wordpress.com/2016/08/17/der-erste-kontakt/

**Comment by bouncyball-git** [comment] 2018-02-14 19:20
Unfortunately I don't read German but pics are self explanatory and cool :)

**Comment by bouncyball-git** [comment] 2018-02-14 19:35
@masc4ii 
Done, uploaded

Let's close this issue.

**Closed by bouncyball-git** 2018-02-14 19:35 UTC
Labels: bug

**Comment by masc4ii** [comment] 2018-02-14 19:39
RELEASED!

**Comment by ilia3101** [comment] 2018-02-14 19:40
🎉  Yay finally!Y!

@seescho Wow that is an amazing picture
