### ISSUE TITLE
MLV export for cutting or averaging.

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#65] opened 2017-12-30 17:18 UTC
I want to implement some stuff I'm missing here:

1. Export cut MLV with or without audio.
2. Export averaged, one frame MLV (darkframe).
3. Add darkframe subtraction support to llrawproc.

What do you think?

**Comment by bouncyball-git** [comment] 2017-12-30 17:34
@masc4ii: For this I'm gonna need some (little) help from you on gui part.

OT: btw pixel interpolation methods now default to method 2 for both focus and bad pixels. I think we need to change defaults to method 1 also for both (it is more effective). Method 2 needed only if CS also active and there are post interpolation artifacts.

**Comment by masc4ii** [comment] 2017-12-30 18:31
Sounds cool. Say what you need and how I can help with the GUI and I will support you as good as I can. 
OT: so I set both methods to = 1 by standard? No problem...

**Comment by masc4ii** [comment] 2017-12-30 18:33
So there will be a new export codec "MLV" with the options "Standard" and "Averaged Frame"? And then we add a new function startExportMlv? Then you could start same as when you did cdng.

**Comment by bouncyball-git** [comment] 2017-12-30 19:24
Yup! you are picking my thoughts on the fly :)

**Comment by masc4ii** [comment] 2017-12-31 11:42
Prepared it for you. Have fun! If something is missing, let me know it! ;-)

**Comment by masc4ii** [comment] 2017-12-31 12:40
Two questions:
- can we fps override a exported MLV? If not I can disable the option.
- can a MLV be overwritten? I guess not, so I forbid that?

**Comment by bouncyball-git** [comment] 2017-12-31 13:03
> can we fps override a exported MLV? If not I can disable the option.

I thought about it and it is easyly doable but if MLV has audio then we should restrict audio exporting because it won't sync unless audio resampling is implemented (what, as you understand, is a whole another story and out of our goal's scope). What do you think? Maybe let the fps alone and restrict as you said?

> can a MLV be overwritten? I guess not, so I forbid that?

Do you mean overwrite original MLV? If yes then restrict it :)

**Comment by bouncyball-git** [comment] 2017-12-31 13:07
Maybe in the future with working WB picker we can implement manual WB of exported MLV.

**Comment by bouncyball-git** [comment] 2017-12-31 13:11
Also I'm not gonna implement lj92 compressing of the exported MLV. I will copy the original raw from source to destination. If it is lossless from the canon it will be lossless in the exported one, otherwise uncompressed. The cut MLV a bit tricky because of audio but I have very simple idea how to circumvent this.

**Comment by bouncyball-git** [comment] 2017-12-31 13:21
Oh! And we have to restrict debayer combo box under DNG and MLV export dialogs as well.

**Comment by masc4ii** [comment] 2017-12-31 13:29
Okay. debayer is restricted, and also audio vs fps override. I will implement something to not overwrite original mlv.

**Comment by bouncyball-git** [comment] 2018-01-02 10:33
Happy New Year to Everyone!

**Comment by ilia3101** [comment] 2018-01-02 12:21
```
Export averaged, one frame MLV (darkframe).
Add darkframe subtraction support to llrawproc.
```
I've wanted to add these things very much too, easiest way to do it would be to add a function to MLV Object like `setMlvDarkFrame(mlvObject_t * video, char * darkFrameMlvPath);`, which just creates another mlv object and averages all of the frames in that file, and uses it as a dark frame.

**Comment by masc4ii** [comment] 2018-01-02 12:37
Wouldn't that be very slow, calculating the averages for every clip then? I thought to export a averaged MLV with just one frame and load this everytime you need it.

**Comment by bouncyball-git** [comment] 2018-01-02 14:15
@ilia3101: Averaging of current active clip? If you mean that, NO :) this will be useless. For dark frame averaging you must record separate MLV with lens cap on and with the same settings as actual clip will be. Give me some time I already have draft implementation.

Of course we could add the buffer pointer to the mlv object but I think it will be better to add it to llrawproc object (which is also unique for clip). In raw correction there will be added one more setting to load darkfranme MLV file. I could introduce any new file format but IMHO we should keep compatibility with mlv_dump to use produced darkframes anywhere.

**Comment by bouncyball-git** [comment] 2018-01-02 14:38
Because I want to add not only averaged MLV export but also standard cut MLV export (with audio), it will take some more time to code this.

There is some aspects to consider. For example:

WBAL, LENS, RTCI block are repeatable or triggered by event. e.g:

WBAL can be changed in the middle of recording like LENS header parameter focal length if you change it for your zoom lens during recording. In this case new LENS block is inserted by event and all following frames have these settings until next event will trigger and so on. This all is supported by MLV and even implemented to mlv_rec. Hence there can be more than one WBAL, LENT header blocks in the MLV.

In short I have to decide include them to the cut MLV or not. They can be omitted because none of existing software use this info and feature :) (we can be 1st who uses it but I don't see real use case for now). There is also VERS block which repeats several times depending on the ML modules loaded to record all versions and commits of hose modules to debug in case of the corrupted MLV data. It can be omitted too - if mlv cut and read correctly theoretically we can say that this info is not interesting further. Anyway this info could be read from the original, not edited.cut MLV.

So there is much to think about :) not to say that inserting cut audio is quite tricky. Doing this is fun for me but will take some time.

**Comment by bouncyball-git** [comment] 2018-01-16 08:47
I've been busy with those f...g focus pixels last week some new changes because of latest development of lossless raw on focus pixel affected cameras (updated my 'fpmutil' and 'mlv_dump os'), I think it is over for now, at least almost over and I've ported those goodies to mlv app too with this [commit](https://github.com/ilia3101/MLV-App/commit/e9e65a028e4440f7edde46b18beb5fafbcfde86a). 

Will update this thread when all is sorted out.

**Comment by bouncyball-git** [comment] 2018-01-20 16:14
I committed 1st working version w/o audio frame support for now. Normal export only no averaging yet.
1. Cut is workig as expected (I hope so)
2. The MLV App inserts it's name and version into VERS block header :)

**Comment by bouncyball-git** [comment] 2018-01-20 17:23
@masc4ii 

I've got one question. Is audio loaded by loadAudio( mlvObject_t *pMlvObject ) and the buffer can be used during export? Or I have to use getMlvAudioData() from audio_mlv.c to load audio to the separate buffer and manupulate on it?

In short what is the correct way to grab the audio buffer when exporting queue?

**Comment by bouncyball-git** [comment] 2018-01-20 17:25
I prefere to use already loaded audio buffer for performance reason.

**Comment by masc4ii** [comment] 2018-01-20 17:47
loadAudio is only called, if the MLV is opened. I'm not sure, if it is when exporting (MLV is not fully loaded there). Audio is also shortend to the number of frames in comparison to the original audio. Atm there is no way to access to the buffer in AudioPlayback.cpp from MainWindow.cpp. 
All in all I think loading audio from getMlvAudioData is the safest and easiest way, maybe not the fastest...

**Comment by bouncyball-git** [comment] 2018-01-20 18:36
OK understood :) thank you.

**Comment by masc4ii** [comment] 2018-01-21 11:36
One question: would it be theoretically possible to export a normal MLV as lossless MLV? That would save a lot of diskspace when archiving the files - CDNG can't be read by our app.

**Comment by bouncyball-git** [comment] 2018-01-21 12:52
Compression is possible and mlv_dump does this, but I did not intend to implement this in here. However If you'd like this feature I'm gonna think how to add this after audio part is done.

One question about audio data buffer that we use is always int16_t not uint16_t (in reality it should be unsigned). So my question is: is there at least one reason to use signed values there? I mean in audio signal drawing routines etc...

**Comment by masc4ii** [comment] 2018-01-21 13:06
Okay, was just a question... if one you have nothing to do, maybe you can it implement ;-)

Hm... that depends on the audio file. But if I remember right, nearly all or all 16bit audio is int16, 8bit audio is uint... but I may be wrong. I don't find this information in my docs. :-( Somewhere I found tables about that.

**Comment by bouncyball-git** [comment] 2018-01-21 13:15
> if ones you have nothing to do, maybe you can it implement ;-)

I promise :)

OK regarding audio signness. I'll leave it as is.

**Comment by bouncyball-git** [comment] 2018-01-21 14:41
Added AUDF support, please share your findings :)

**Comment by bouncyball-git** [comment] 2018-01-21 15:04
@masc4ii: the FPS override for MLV export is kinda pointless (if has audio in it then 2 times pointless), besides we already have this feature for DNG export.

Could you be so kind, disable it for MLV export dialog ok :)

**Comment by masc4ii** [comment] 2018-01-21 15:10
Sure, I'll do.

**Comment by masc4ii** [comment] 2018-01-21 15:13
The wav window in the GUI is always empty... :-(

**Comment by masc4ii** [comment] 2018-01-21 15:29
Okay. For me it seems to work. I only have one (very small) finding:
I have recorded a sync test file. In the original the sync is maybe 1 frame false. No big deal. Now I shortend this file and loaded it again. The sync looks better than in the original file... hmmm :-?
But maybe my audio drawing is not perfect.

**Comment by bouncyball-git** [comment] 2018-01-21 16:00
Yes I found this bug too and fixed please try again.

**Comment by bouncyball-git** [comment] 2018-01-21 16:02
It was exactly 1 frame off :), cut_audio_size was calculated for real frame count -1 ;)

**Comment by masc4ii** [comment] 2018-01-21 16:05
Now both MLVs look the same I think...

**Comment by bouncyball-git** [comment] 2018-01-21 16:08
Well.. I think it is not related to sync. The audio was just 1 frame shorter, and 1 frame MLV can not be exported.

For sync you can find 1st AUDF and 1st VIDF and compare their block header time in microseconds.

**Comment by bouncyball-git** [comment] 2018-01-21 16:09
I think it is always some microseconds off, because I have not seen the MLV which audio and video frame times are exact match.

**Comment by bouncyball-git** [comment] 2018-01-21 16:11
In cut MLV I preserve 1st RTCI and all block times because if someone someday decides to get actal recorded time code this will be possible.

**Comment by bouncyball-git** [comment] 2018-01-21 16:12
btw we could implement timecode to our slider. RTCI + time according to FPS.

**Comment by masc4ii** [comment] 2018-01-21 16:28
When I heard it, I thought it was okay. Just the wav graphic did not fit to the frames.
RTCI + time according to FPS? Don't understand...

**Comment by bouncyball-git** [comment] 2018-01-21 16:55
No somewhere print the current frame timecode in the format 00:00:00.00 <- last is frames.

I added erro dialogs to the MLV export function (one outside the loop for header and second in the loop for frames). Please review my changes, something is incorrect there. To check this in both IFs just add ! (not) before funcion 1 and then to function 2 in the loop.

**Comment by bouncyball-git** [comment] 2018-01-21 17:10
> Just the wav graphic did not fit to the frames as before.

Is it noticeable that much? I don't have any MLVs for syncing, would be nice to have one. Have no camera atm.

**Comment by masc4ii** [comment] 2018-01-21 18:04
First Messagebox did not work in the right way I think?! Can fix it. Or is there another problem?
I can upload my synctest clip (a very professional one :o) ).

Okay, understood with the timecode. But how does that work for fps with decimals? 25, 24, 30 fps I understand. But 23.96... how looks the timecode then? I can't understand what is shown after the first second.

**Comment by masc4ii** [comment] 2018-01-21 18:27
Here comes my special sync test mlv: https://www.dropbox.com/s/eo3wlb5ehp3fpa0/SyncTest.MLV?dl=0
I hope my daughter gives a copyright for her little book. :o)

**Comment by bouncyball-git** [comment] 2018-01-21 18:32
Thank you man :) I'll check all this tomorrow.

Regarding timecode... you are right. 1/23.976 microsec or 1/24 microsec does not matter but hmm I guess it is also goes to 00:00:00.24... IDK :P we should look at premiere or fcpx.

**Comment by bouncyball-git** [comment] 2018-01-21 18:46
Love that little book :D. After exporting to x264 it seems almost in sync.

> But I have a graphical idea how to realize that... wohoouu.

I'm Intrigued!

**Comment by bouncyball-git** [comment] 2018-01-22 17:53
@masc4ii: Added last feature requested by you :). LOTs of changes! :P

**Comment by bouncyball-git** [comment] 2018-01-22 18:47
I encountered some errors with audio playback of cut MLV. When playback stops at the end error displayed:

`
QAudioOutput(pulseaudio): pa_stream_write, error = Invalid argument
`

Can someone confirm that large cut MLV has some audio problem 2 the end of the file?

**Comment by masc4ii** [comment] 2018-01-22 19:39
Yeah, very nice! Thank you so much! For me that works good. 
How large was your file? I tested with around 600 frames 1:1 or made 550 frames and that was working without problems. Could you describe more detailed what you did? Compressed, Fast Pass?

**Comment by bouncyball-git** [comment] 2018-01-23 07:19
Fast pass, cut file is 1176MB 339frames.

BTW could be audio size more then 4294967296 bytes (4.3gb, uint32_t max value) ? :P
What I'm doing is for the simplicity writing just one big AUDF frame (cut or whole audio of the MLV)

**Comment by bouncyball-git** [comment] 2018-01-23 11:44
I did it! Fixed the playback end error and the audio length now is perfectly aligned.

I think WAV output also needs the same alignment, I remember in WAV header 4kb alignment is mandatory.
'theoretic_size' to multiple of 4096
'in_offset' to be always even

What do you think?

**Comment by masc4ii** [comment] 2018-01-23 11:58
Yay. Cool!

Sry. No idea. But if the header tells 4kb alignment is mendatory... do we have a choice?

**Comment by bouncyball-git** [comment] 2018-01-23 13:51
> do we have a choice?
I'll update this part.

**Comment by bouncyball-git** [comment] 2018-01-27 09:27
All 3 modes for MLV export is ready, please try all 3 again and share your findings.

**Comment by bouncyball-git** [comment] 2018-01-27 09:33
The only thing that is not implemented yet to average frame if input is compressed MLVs, will follow...

**Comment by masc4ii** [comment] 2018-01-27 11:06
I tried the average export. 1st try: crash in saveMlvAVFrame. But I can't reproduce it.
Now I get averaged MLVs. But, when opening, it looks like the something is not right. Look the pinkish shadows:
![m23-1205_frame_1](https://user-images.githubusercontent.com/30245296/35471383-75699828-035a-11e8-92a2-6a8ee25929ae.png)

**Comment by bouncyball-git** [comment] 2018-01-27 11:12
Pinkish shadows does not matter for dark frame :), it is OK. If we also try to use this feature like filter or something it is better do this post debayer on rgb image.

The only thing is bothering me the first crash, because I also experienced only one crash for 1st run of this code... which is strange. I can not reproduce it after that either ;).

**Comment by bouncyball-git** [comment] 2018-01-27 11:20
If you will average the MLV recorded by lense cap on this will be real averaged dark frame and can be subtracted from the image, this feature will also follow when I'm done with compressed MLV importing.

Then I will add the dark frame subtraction feature to the llrawproc section and I will need your GUI support :)

I'm also gonna  (there even implemented some preliminary stuff already) add DARK block as a part of exported MLV, so MLVs produced by MLV App will include their darkframe inside and will be auto detected and loaded.

**Comment by masc4ii** [comment] 2018-01-27 11:26
Do you mean that works, when substracting pink from black+noise? Or "does it look different" on non-debayered state?

What do we need in the GUI? An area "darkframe substraction", a selection for a file name and a checkbox "Enable"?

**Comment by bouncyball-git** [comment] 2018-01-27 11:32
Q1. Yes it is working. It looks pinkish just after MLV App processing, try to export DNG and process with some other software.
Q2. As always you are catching my thoughts on the fly! :D, plus some fine tuning tweaks which I will tell you when I decide how it will work at the end.

**Comment by bouncyball-git** [comment] 2018-01-27 11:34
Oh and please process your clip with 'mlv_dump -a -o averaged.mlv input.mlv' and load averaged.mlv to MLV App and compare with our resulted MLV. It should also look pinkish.

**Comment by masc4ii** [comment] 2018-01-27 12:32
When I process the clip with mlv_dump there is no pink in the shadows:
![averaged_frame_1](https://user-images.githubusercontent.com/30245296/35471968-81483c4c-0366-11e8-8db4-c0e9b2d5bf89.png)
Do you like it?
![bildschirmfoto 2018-01-27 um 13 27 34](https://user-images.githubusercontent.com/30245296/35471971-8a4e30b2-0366-11e8-970c-ffc26ffa1211.png)

**Comment by bouncyball-git** [comment] 2018-01-27 14:21
Hmm... Thanks for testing I'll check this out when get to my Linux box.

Yes the GUI is what it should be! Great!

**Comment by bouncyball-git** [comment] 2018-01-27 14:28
I've got an idea, let's make the the tool buttons 3.

Off | Int | Ext

means off is no processing, Int use dark frame frame found in MLV, Ext use external file.

If MLV dark detected Int will be automatically selected with the option to turne it off or even load from a file.

In case of no MLV dark frame found, Int will be disables (grayed out)

What do you think?

**Comment by bouncyball-git** [comment] 2018-01-27 15:09
The most beautiful thing is, adding of DARK block will not break any spec of MLV and compatibility with other software.

**Comment by masc4ii** [comment] 2018-01-27 15:34
Puh... a lot ifs to implement... hope that works. ;-)

**Comment by masc4ii** [comment] 2018-01-27 15:38
And how do we get the darkframe into the MLV?

**Comment by bouncyball-git** [comment] 2018-01-27 15:46
When exporting MLV from MLV App:
1. If MLV already includes DARK, it will be automatically included in output.
2. If MLV already includes DARK, but Ext is active and dark frame file is loaded, external will be included.
3. If MLV does not inlcude DARK, but Ext is active and dark frame file is loaded, external will be 
inclued.
4. No Int no Ext... nothing will be included ;)

**Comment by masc4ii** [comment] 2018-01-27 17:15
Okay... hope that works... commited.

We need:
getMlvHasInternalDarkframe( m_pMlvObject ) -> true/false
That switches the "Int" button enabled/disabled.

OFF=0, Ext = 1, Int = 2.
![bildschirmfoto 2018-01-27 um 18 15 32](https://user-images.githubusercontent.com/30245296/35474401-174fcb52-038e-11e8-8c74-ca9efc01b229.png)

See the "TODO: ..." in the code.

**Comment by bouncyball-git** [comment] 2018-01-27 18:10
Great! Thanks :D

**Comment by bouncyball-git** [comment] 2018-01-27 18:14
Can you see all button size mismatches under Linux?! ;)
![screen](https://user-images.githubusercontent.com/17232233/35474965-7e8bdf2e-03af-11e8-8733-29612f77e5c3.png)

**Comment by masc4ii** [comment] 2018-01-27 18:27
LOL... I'll have a look. On OSX all have the same size. So I will compare the settings ;-)

**Comment by masc4ii** [comment] 2018-01-27 18:29
Can you please check again?

**Comment by bouncyball-git** [comment] 2018-01-27 18:32
Bingo!
![screenshot from 2018-01-27 22-31-41](https://user-images.githubusercontent.com/17232233/35475095-e8771690-03b1-11e8-8ddb-25bab8581d84.png)
It's just load button is a bit smaller.

**Comment by masc4ii** [comment] 2018-01-27 18:34
Hm... but here I can't do much. The problem is, that there is no text inside. And each OS has different fonts, so I can't fix it. I could delete the icon and name it "Open", that may be short enough...

**Comment by bouncyball-git** [comment] 2018-01-27 18:35
I guess I can live with it :), forget about it!

**Comment by masc4ii** [comment] 2018-01-27 18:39
Hm... but you were right... it does not look very professional. Could you try again? Maybe I found a flag ;-)

**Comment by bouncyball-git** [comment] 2018-01-27 18:57
Now it's perfect :)
![screenshot from 2018-01-27 22-57-15](https://user-images.githubusercontent.com/17232233/35475313-7e676d3c-03b5-11e8-8fcc-3f78d6793beb.png)

**Comment by bouncyball-git** [comment] 2018-01-27 18:59
Can we bring dark gui to the top and the pattern noise to the bottom? Or it is very big PITA?

**Comment by masc4ii** [comment] 2018-01-27 19:12
Like that?
![bildschirmfoto 2018-01-27 um 20 12 25](https://user-images.githubusercontent.com/30245296/35475417-7072ecc2-039e-11e8-837a-eb011e0977a9.png)

**Comment by bouncyball-git** [comment] 2018-01-27 19:49
This is beautiful!!!

Let's make dual iso interpolation default amaze ok?

**Comment by masc4ii** [comment] 2018-01-27 20:01
Done. :-)

**Comment by bouncyball-git** [comment] 2018-01-28 09:01
Thanx :)

**Comment by bouncyball-git** [comment] 2018-01-28 09:04
One more thing ;) Please add Ctrl-Alt-R hot key for Reset Receipt.

**Comment by bouncyball-git** [comment] 2018-01-28 09:57
Fixed bug causing calculating incorrect averaged values. No pink tint any more.

Now averaged data produced by MLV App is identical to the data produced by the following command:

`mlv_dump --no-fixcp --no-stripes -a -o averaged.mlv input.mlv`

**Comment by bouncyball-git** [comment] 2018-01-28 09:59
I guess averaging and basically MLV exporting journey is over, let's move to the actual dark frame subtraction baby :)

**Comment by masc4ii** [comment] 2018-01-28 10:50
Sry, forgot the shortcut because of all the topics. Done. 
Will try the averaging. 
I am very excited what the subtraction baby will bring! :-)

**Comment by bouncyball-git** [comment] 2018-01-29 16:31
@masc4ii 

I wanna ask you something :)
To change the behavior of dark frame loading part.

The loading button and the file name string editing widget should be enabled only when Off tool button is active. I think this is not so difficult to do right?

**Comment by masc4ii** [comment] 2018-01-29 18:52
My concept was a bit different:
you can change the filename and click the load button always. BUT: if the filename does not exist the darkframe is switched to off automatically. See the code, I made comments for you, where to call what (jsut search for "TODO"). So in the end the user is leaded automatically. Is this okay for you?

**Comment by bouncyball-git** [comment] 2018-01-29 20:33
Yes I reviewed all code already.

I prefer to load dark frame only when Ext/Int is pressed, the chance to load file or edit file name path/name any time is complicated things a lot.

1. By default there will be active Off and loading button, name will be empty but active too. Ext/Int disable (as it is now, very good)
2. If file opened or name manually entered then this name will be set to the member of the structure and Ext button activated (like it does now, also very good), but dark frame not gonna be loaded until Ext is pressed.
3. If Ext pressed frame will be loaded and ready to use, **_load button and name field disabled_** (**_name frozen not editable but active_**), **_to avoid the case when current loaded dark frame does not match the one that newly loaded/entered to the name field, reloading/freeing frame buffer on load/name change really complicates things a lot and we do not need this!_**
4. If internal DARK block detected Int also be active an usable.
5. If Int pressed external dark frame will be freed and internal loaded
6. If Ext pressed internal freed and external loaded
7. If Off is pressed frame will be freed and pointer NULLed, load button and name field active again and ready to be used. (dark frame processing will be off of course)

I'm sorry for a long post but this is how it will be really nicely done. **_Not checking anytime if new filename loaded and trying to load frame! (not good and misleading also adds more unneeded checks)_**

**Comment by masc4ii** [comment] 2018-01-29 20:48
> to avoid the case when current loaded dark frame does not match the one that newly loaded/entered to the name field, reloading/freeing frame buffer on load/name change

Ahh... okay, I understand. Hm. I can change that, no problem. I was thinking from the users view and thought it is strange to block the elements. But I can understand your reason... ;)

**Comment by bouncyball-git** [comment] 2018-01-29 20:51
Cool thanks :), Receipt will hold only active tool button value and file name (I guess only if active button is not Off)

**Comment by masc4ii** [comment] 2018-01-29 20:55
Done. What receipt does you can test. This should be completely ready.

**Comment by bouncyball-git** [comment] 2018-01-29 20:57
Thanks again I hope it will be done tomorrow, at least subtracting external DF.

**Comment by masc4ii** [comment] 2018-01-29 20:58
Sounds good. Maybe I can test it in the night then... :o)

**Comment by bouncyball-git** [comment] 2018-01-29 21:03
Be my guest :)

**Comment by bouncyball-git** [comment] 2018-01-30 14:19
I don't like this auto setup:

```
    //Auto setup at first full import, else get from receipt
    if( receipt->darkFrameEnabled() == -1 )
    {
        if( llrpGetDarkFrameIntStatus( m_pMlvObject ) )
        {
            setToolButtonDarkFrameSubtraction( 2 );
        }
        else
        {
            setToolButtonDarkFrameSubtraction( 0 );
        }
    }
    else
    {
        setToolButtonDarkFrameSubtraction( receipt->darkFrameEnabled() );
    }
```

I think we have to leave only this:

`setToolButtonDarkFrameSubtraction( receipt->darkFrameEnabled() );`

**Comment by bouncyball-git** [comment] 2018-01-30 14:23
Also something strange is happening here. This func called twice in a row

```
//Darkframe Subtraction On/Off changed
void MainWindow::toolButtonDarkFrameSubtractionChanged( void )
{
    llrpInitDarkFrame( m_pMlvObject, toolButtonDarkFrameSubtractionCurrentIndex() );
    //Blocking filename while active
    if( toolButtonDarkFrameSubtractionCurrentIndex() == 1 )
    {
        ui->lineEditDarkFrameFile->setEnabled( false );
        ui->toolButtonDarkFrameSubtractionFile->setEnabled( false );
    }
    else
    {
        ui->lineEditDarkFrameFile->setEnabled( true );
        ui->toolButtonDarkFrameSubtractionFile->setEnabled( true );
    }
    resetMlvCache( m_pMlvObject );
    resetMlvCachedFrame( m_pMlvObject );
    m_frameChanged = true;
}
```

I can not track this behavior down... why.

**Comment by bouncyball-git** [comment] 2018-01-30 14:26
Calling twice in a row causes the dark frame buffer to be freed on second call, so it is not working...

**Comment by bouncyball-git** [comment] 2018-01-30 16:32
@masc4ii 

With last commit it is WORKING :-D, but... double calling persists! Please help me to get rid of this issue.

**Comment by bouncyball-git** [comment] 2018-01-30 17:10
[Here](http://nic.caucasus.net/mlvapp/) are 2 files, 1st small one is the dark frame made by MLV App. 2nd file is the test file for which this dark frame was made. Happy testing :)

**Comment by masc4ii** [comment] 2018-01-30 18:45
Hi, I am back from a 700km trip. I think I know why it is called twice. I'll check if I am right...

**Comment by masc4ii** [comment] 2018-01-30 19:15
Cool. That works! The red/pink color looks better/more natural now. On my 5D2 footage, the left side of the picture is often way brighter than the right at high ISO. This can be corrected now. 
You said to comment out the auto detection because of speed reasons... you really want to do so? For me the speed is nearly 1:1 with:without darkframe subtraction. I loos maximum 0.5 fps, that is not bad.

**Comment by masc4ii** [comment] 2018-01-30 19:40
Did you implement the internal feature? I don't get that to work. The subtraction runs very well! :)

**Comment by bouncyball-git** [comment] 2018-01-31 07:43
> Hi, I am back from a 700km trip. I think I know why it is called twice. I'll check if I am right...

Whoa some trip! This is more then my country's length ;). It is like if I would drive to the seashore and back to the capital, sometimes it happens but I never liked doing this, long car trips are not for me :).
BTW it is not the first time I'm experiencing double calling from QT interface, it was just not so essential then.

> Did you implement the internal feature? I don't get that to work. The subtraction runs very well! :)

Nope, not yet :) It needs MLV export code to be updated.

> You said to comment out the auto detection because of speed reasons... you really want to do so? For me the speed is nearly 1:1 with:without darkframe subtraction. I loos maximum 0.5 fps, that is not bad.

I think we can leave it as is :) it is really fast. But it should trigger llrpInitDarkFrame() at the same time to load and unpack the frame into 16 bit buffer to be ready to use.

The same could be done with Ext mode, when file loaded (or correct file name is entered manually) switch to Ext mode and trigger llrpInitDarkFrame()

We have to think about it togather

**Comment by masc4ii** [comment] 2018-01-31 09:35
Hehe, what is your country?

Yes, I think all toolButtons which work like radioButtons have this problem. They call the function when beeing enabled AND disabled. So I have to write something, that they call only the function when get checked. If you have other elements where this happens, let me know!

So you'll implement internal darkframe export and then we have v0.14?
I had some problems I did not understand, when enabling another toolbutton after having clicked one. That means clicking load and if success enabling ext was a big problem... :-( That does not work with the GUIs style sheet and distroyed the themes colors (whyever, hope I find the reason one day). When triggering it without a toolButton click (e.g. receipt or import) there is no problem.

**Comment by bouncyball-git** [comment] 2018-01-31 14:47
I'm [here](https://www.google.ge/maps/place/Tbilisi/@41.7325661,44.7688134,12z/data=!3m1!4b1!4m5!3m4!1s0x40440cd7e64f626b:0x61d084ede2576ea3!8m2!3d41.7151377!4d44.827096?hl=en) :-D

> If you have other elements where this happens, let me know!

I'll check.

If all is gonna be sorted out why not release 0.14?

> When triggering it without a toolButton click (e.g. receipt or import) there is no problem.

there are 2 functions for detecting Int and Ext status.
int llrpGetDarkFrameExtStatus(mlvObject_t * video)
int llrpGetDarkFrameIntStatus(mlvObject_t * video)

One of them we even using here, in mainwindow.cpp
line 2267 ui->toolButtonDarkFrameSubtractionInt->setEnabled( llrpGetDarkFrameIntStatus( m_pMlvObject ));

We could also call llrpGetDarkFrameExtStatus() after opening file to detect the Ext status and set Ext button active. If it will work in previous case why it did not in the second?

**Comment by bouncyball-git** [comment] 2018-01-31 14:51
If this will not work we just give up all auto detection and by default off button will be active.

**Comment by bouncyball-git** [comment] 2018-01-31 16:13
Hey man I'm scratching my head and can not understand what really actualize variable is doing. In short I can not understand this code:

`void MainWindow::setToolButtonDarkFrameSubtraction(int index)
{
       //Switch Darkframe Subtraction to OFF if internal was selected and no internal data is available
       if( !llrpGetDarkFrameIntStatus( m_pMlvObject ) && index == 2 ) index = 0;

    bool actualize = false;
    if( index == toolButtonDarkFrameSubtractionCurrentIndex() ) actualize = true;

    switch( index )
    {
    case 0: ui->toolButtonDarkFrameSubtractionOff->setChecked( true );
        break;
    case 1: ui->toolButtonDarkFrameSubtractionExt->setChecked( true );
        break;
    case 2: ui->toolButtonDarkFrameSubtractionInt->setChecked( true );
        break;
    default: break;
    }
    if( actualize ) toolButtonDarkFrameSubtractionChanged( true );
}`

if index == toolButtonDarkFrameSubtractionCurrentIndex() does't it mean DO NOTHING? But code does the opposit ;) (calls toolButtonDarkFrameSubtractionChanged( true ))  

I'm really lost hahaha...

**Comment by masc4ii** [comment] 2018-01-31 18:04
Nice city! :-) Looks good on Google!

Yes, if the detection is triggered by an receipt or the file input, we can do a autodetect. 

The actualize variable is for actualizing the variable. That means: if e.g. the Ext button was select before, you change the clip, I load the receipt where again Ext is selected. So `index == toolButtonDarkFrameSubtractionCurrentIndex()` and  `ui->toolButtonDarkFrameSubtractionExt->setChecked( true )` would do absolutely nothing. So your functions would never be called. For exactly this case I manually call `toolButtonDarkFrameSubtractionChanged` what calls your functions.

**Comment by bouncyball-git** [comment] 2018-01-31 18:17
Thanks :) and which is your city? I guess it is in Germany.

Ok got it ( a least half of it ;) ). What I really understood is that I need to rewrite a lot of code for making exporting work like it should taking in consideration receipt settings which sets setsliders function every time file loaded or to be exported :)... Phew... need to change llrawproc function call to DF. This function should every time initialize all DF stuff not only subtract the frames like it does now. In short it must do things like bad pixels/stripes/etc are working. Well... this gonna happen only tomorrow...

**Comment by bouncyball-git** [comment] 2018-01-31 18:26
One question: during export if settings are derived from receipt and buttons are enabled accordingly does it also make call to appropriate functions like for example on_darkFrameExt() to set llrawproc DF variables? e.g. set dark_frame to 0, 1 or 2? Somehow it is done for other llrawproc variables...

**Comment by bouncyball-git** [comment] 2018-01-31 18:28
Well I'm lost again but never mind. New day - fresh mind :) buy till tomorrow.

**Comment by masc4ii** [comment] 2018-01-31 18:35
Yes, my actual village is [this one.](https://www.google.ge/maps/place/Ilmenau/@50.6921946,10.8252605,12z/data=!3m1!4b1!4m5!3m4!1s0x47a38d0b18a219a5:0x4208ec174357590!8m2!3d50.6843502!4d10.9254728?hl=en)

Yes, on export, setSliders is called. This sets the sliders what calls e.g. toolButtonDarkFrameSubtractionChanged, and this sets your functions (link can be found in the .ui under signals&slots).

**Comment by bouncyball-git** [comment] 2018-02-01 15:40
Nice! Unfortunately I've been in Germany just once. In Hanover on Cebit exhibition and lived [here](https://www.google.ge/maps/place/relexa+Hotel+Bad+Salzdetfurth/@52.0872994,9.9952006,14z/data=!4m15!1m9!2m8!1sHotels!3m6!1sHotels!2s52.0578423,+10.0098516!3s0x47bab248fd8c7005:0x425ac6d94ac5e30!4m2!1d10.0098516!2d52.0578423!3m4!1s0x47bab23795d49531:0xc6e173e376d473ac!8m2!3d52.072966!4d10.016111?hl=en), very  cozy small town :), also spent some time in Berlin. I'd like to live in a calm village. In my city's streets there are almost 1 million cars and crazy pollution :) huge traffic jams and it is so hard to stop the car anywhere, even at my house ;).

I have to rewrite the code, it does not work with DNG export, I'm sure it will not work for other exports too... (please test) it now works for preview only.

**Comment by masc4ii** [comment] 2018-02-01 15:53
Yes, it is very calm here and there is a lot of forest around. ;)

Tested export - it is right, that does not work. And also after export, when coming back to preview, there is no way to see the subtracted frame again. You have to switch between the clips and it works again.

**Comment by bouncyball-git** [comment] 2018-02-01 16:01
Yes right after export preview also dead.

I know why, I messed it up (it is quite while when I've implemented llrawproc) I forgot how llrawproc works now I'm starting remembering. The initialization of DF stuff should be in the llraproc code not just outside of it. Then it will work for both export and preview.

**Comment by bouncyball-git** [comment] 2018-02-01 16:02
Our project got quite complicated... but who loves documenting things up? :P

**Comment by masc4ii** [comment] 2018-02-01 17:11
If you remember what you did... all is fine ;-)
I have the same problem. When I started it was nice and small. Now... hmmm... after some minutes I know where to screw. 
"The code is documentation enough." Or what do you think?! :-D

**Comment by bouncyball-git** [comment] 2018-02-01 18:34
Well... If it is commented at least a bit to give a hint why one pointer equals to some other pointer in one case and to another in second case than you are OK ;) (well... almost)

You gotta look at original mlv_dump's source... and my huge changes too... crazy ride on enormous branching :). Sometimes it take a LOT more then "some minutes" to even remember what is what, not saying anything about understanding it from scratch. And I hope you never look at dcraw sources, pure Amazonian tropical jungle grown from 90ies till today ;).

**Comment by bouncyball-git** [comment] 2018-02-01 18:46
Dmilligan's source of MLVFS is very well structured and easier to understand, despite it is pure C and very cool piece of multy threaded software, in opposite Baldand's mlrawviewer is one hard to understand knot. BTW do you like/use python?

**Comment by masc4ii** [comment] 2018-02-01 19:47
Hm... ten years ago I was playing a bit with Phyton, but I never understood why so many people love it... :-) But there will be reasons I don't know...

**Comment by bouncyball-git** [comment] 2018-02-02 07:37
>  But there will be reasons I don't know...

I guess the main reason is huge lib support and lot of them are written in C/C++ so performance wise they are good. I personally, despite several attempts (1st attempt was in 90ies) to adopt this language, have failed b/c I hate it every time I see it :P.

**Comment by bouncyball-git** [comment] 2018-02-02 07:45
OT: Every time I look at your timecode/duration I love it :) btw I left it on default location.

**Comment by masc4ii** [comment] 2018-02-02 12:10
Hehe, thanks. I also use it a lot - I never thought it before. For the future I would like to have two icons in the left part of the element:
- a water drop: Dropmode on/off
- a loudspeaker: Audio on/off
But I haven't found some nice and free monochrome icons for that yet. (Now you always must look in the menu what setting you have.)

**Comment by bouncyball-git** [comment] 2018-02-02 18:30
Yes right would be very nice!

We got real OT here :P, so... about the subject:

I've updated lot of things - separated the code and added 2 dedicated c/h files for dark frame stuff which is good for overall structuring. Now app can export MLV with internal dark block if dark file loaded and Ext is on during exporting. Other exports also should work as expected did not try it, have to go home, please try and share findings. Despite internal DARK block detection on loading exported MLV, Int button activated but does nothing ATM. To be continued :)

**Comment by masc4ii** [comment] 2018-02-02 21:09
Cool. Export working! So far I found no bug... good job!

**Comment by bouncyball-git** [comment] 2018-02-03 12:19
I hope I've finished Dark Frame journey. MLVs exporting with and without DARK block. Exports are working auto detection of DF modes works, recalculation bad pixel and stripes added (b/c DF subtraction happens before them). It now needs testing.

Also I've got suggestion: let's turne off stripe correction by default, is is a bit expensive performance wise, leave only bad pixels as is and focus pixels also auto detected already.

**Comment by bouncyball-git** [comment] 2018-02-03 16:15
I've also added the option for exporting internal dark frame of the clip as a separate darkframe MLV.

Now we have these options:
1. loading external DF
2. inserting DARK to MLV
3. extracting DARK from MLV
4. deleting DARK from MLV

Phew... Please don't tell me there are bugs :P... (hope so)

**Comment by masc4ii** [comment] 2018-02-03 19:04
I tried to extract DARK from MLV when there is no loaded. Export ends with an error - the message could be written out more clear (but this is not soooo important). AND (more important in my eyes): export leaves a corrupted file. Could you delete such files, if export aborts?

**Comment by bouncyball-git** [comment] 2018-02-03 19:16
Do you mean export MLV to include darkframe when Ext not activated?
or
Do you mean extracting darframe from MLV with already built in darkframe?

**Comment by masc4ii** [comment] 2018-02-03 20:00
3.

**Comment by bouncyball-git** [comment] 2018-02-04 11:08
Done.

OT: Also I've got suggestion: let's turn off stripe correction by default, it is a bit expensive performance wise, leave only bad pixels as is and focus pixels also auto detected already. What do you think?

**Comment by masc4ii** [comment] 2018-02-04 11:37
So I set default to Off for vertical stripes? I can do - my 5D2 has no stripes :-D

**Comment by masc4ii** [comment] 2018-02-04 12:04
Done. Time for v0.14?

**Comment by bouncyball-git** [comment] 2018-02-04 15:02
Yes! please ... :)

**Comment by masc4ii** [comment] 2018-02-04 15:19
I think it was Ilia, he likes to add highlights and shadows today. I checked in the version strings already, but lets wait with the release until this is done! ;-)

**Comment by bouncyball-git** [comment] 2018-02-04 15:26
Sure

**Closed** 2018-02-07 11:50 UTC
Labels: enhancement
